namespace ServerEye.Core.Services.OAuth.Providers;

using System.Text.Json;
using Microsoft.Extensions.Logging;
using ServerEye.Core.Configuration;
using ServerEye.Core.DTOs.Auth;
using ServerEye.Core.Enums;
using ServerEye.Core.Interfaces.Services;
using ServerEye.Core.Services.OAuth;

public sealed class GitHubOAuthProvider(
    OAuthSettings oauthSettings,
    ILogger<GitHubOAuthProvider> logger) 
    : BaseOAuthProvider(oauthSettings, logger), IOAuthProvider
{
    public override OAuthProvider ProviderType => OAuthProvider.GitHub;

    public override bool IsEnabled()
    {
        return Settings.GitHub.Enabled;
    }

    public override async Task<OAuthChallengeResponseDto> CreateChallengeAsync(string state, string codeChallenge, Uri? returnUrl)
    {
        Logger.LogInformation(
            "CreateGitHubChallengeAsync called - State: {State}, CodeChallenge: {CodeChallenge}, ReturnUrl: {ReturnUrl}",
            state,
            codeChallenge[..Math.Min(codeChallenge.Length, 20)] + "...",
            returnUrl?.ToString() ?? "null");

        var settings = Settings.GitHub;
        var scopes = "user:email";

        // Add provider prefix to state so we can identify it in callback
        var stateWithProvider = $"github_{state}";
        var redirectUri = Uri.EscapeDataString(settings.RedirectUri.ToString());

        Logger.LogInformation(
            "GitHub OAuth settings - ClientId: {ClientId}, RedirectUri: {RedirectUri}, Scopes: {Scopes}",
            settings.ClientId,
            settings.RedirectUri.ToString(),
            scopes);

        // GitHub doesn't support PKCE, so we don't include code_challenge parameters
        var url = $"https://github.com/login/oauth/authorize?" +
                  $"client_id={settings.ClientId}&" +
                  $"redirect_uri={redirectUri}&" +
                  $"scope={scopes}&" +
                  $"state={stateWithProvider}";

        if (returnUrl != null)
        {
            url += $"&return_url={Uri.EscapeDataString(returnUrl.ToString())}";
        }

        Logger.LogInformation("Generated GitHub challenge URL: {Url}", url[..Math.Min(url.Length, 100)] + "...");

        return new OAuthChallengeResponseDto
        {
            ChallengeUrl = new Uri(url),
            State = stateWithProvider,
            CodeVerifier = string.Empty, // Generated by OAuthService
            Action = null
        };
    }

    public override async Task<OAuthUserInfoDto> GetUserInfoAsync(string accessToken, string? idToken, CancellationToken cancellationToken)
    {
        Logger.LogInformation(
            "GetGitHubUserInfoAsync called - AccessToken: {AccessToken}, IdToken: {IdToken}",
            accessToken[..Math.Min(accessToken.Length, 20)] + "...",
            string.IsNullOrEmpty(idToken) ? "NULL" : idToken[..Math.Min(idToken.Length, 20)] + "...");

        using var httpClient = new HttpClient();
        httpClient.DefaultRequestHeaders.Add("User-Agent", "ServerEye");
        httpClient.DefaultRequestHeaders.Add("Authorization", $"token {accessToken}");

        var response = await httpClient.GetAsync(new Uri("https://api.github.com/user"), cancellationToken);
        response.EnsureSuccessStatusCode();

        var content = await response.Content.ReadAsStringAsync(cancellationToken);
        var userData = JsonSerializer.Deserialize<Dictionary<string, object>>(content, JsonOptions)
               ?? throw new InvalidOperationException("Failed to get user info from GitHub");

        // Get user email (GitHub requires separate API call for email)
        var emailResponse = await httpClient.GetAsync(new Uri("https://api.github.com/user/emails"), cancellationToken);
        emailResponse.EnsureSuccessStatusCode();
        var emailContent = await emailResponse.Content.ReadAsStringAsync(cancellationToken);
        var emailData = JsonSerializer.Deserialize<List<Dictionary<string, object>>>(emailContent, JsonOptions);

        var primaryEmail = emailData?.FirstOrDefault(e => bool.TryParse(e.GetValueOrDefault("primary")?.ToString(), out var primary) && primary);
        var email = primaryEmail?.GetValueOrDefault("email")?.ToString() ?? string.Empty;

        // For GitHub OAuth, if user has an email, it's verified by OAuth flow
        var emailVerified = !string.IsNullOrEmpty(email);

        return new OAuthUserInfoDto
        {
            Id = userData.GetValueOrDefault("id")?.ToString() ?? string.Empty,
            Email = email,
            Name = userData.GetValueOrDefault("name")?.ToString() ?? string.Empty,
            Username = userData.GetValueOrDefault("login")?.ToString() ?? string.Empty,
            AvatarUrl = !string.IsNullOrEmpty(userData.GetValueOrDefault("avatar_url")?.ToString()) ? new Uri(userData.GetValueOrDefault("avatar_url")?.ToString()!) : null,
            EmailVerified = emailVerified,
            RawData = userData
        };
    }

    public override async Task<TokenResponseDto> ExchangeCodeAsync(string code, string codeVerifier, CancellationToken cancellationToken)
    {
        using var httpClient = new HttpClient();
        var settings = Settings.GitHub;
        var tokenEndpoint = "https://github.com/login/oauth/access_token";

        // GitHub doesn't support PKCE, but we log the verifier for consistency
        Logger.LogDebug("GitHub OAuth called with code verifier (not supported by GitHub): {CodeVerifier}", codeVerifier[..Math.Min(codeVerifier.Length, 20)]);

        var parameters = new Dictionary<string, string>
        {
            ["client_id"] = settings.ClientId,
            ["client_secret"] = settings.ClientSecret,
            ["code"] = code,
            ["grant_type"] = "authorization_code",
            ["redirect_uri"] = settings.RedirectUri.ToString()
        };

        using var content = new FormUrlEncodedContent(parameters);

        // GitHub requires Accept header to return JSON instead of form-encoded data
        httpClient.DefaultRequestHeaders.Add("Accept", "application/json");

        var response = await httpClient.PostAsync(new Uri(tokenEndpoint), content, cancellationToken);

        var responseContent = await response.Content.ReadAsStringAsync(cancellationToken);
        Logger.LogInformation(
            "GitHub token response - Status: {Status}, Content: {Content}",
            (int)response.StatusCode,
            responseContent);

        response.EnsureSuccessStatusCode();

        // Manual JSON parsing like Google
        using var jsonDoc = JsonDocument.Parse(responseContent);
        var root = jsonDoc.RootElement;

        var tokenResponse = new TokenResponseDto
        {
            AccessToken = root.GetProperty("access_token").GetString() ?? string.Empty,
            RefreshToken = root.TryGetProperty("refresh_token", out var refreshToken) ? refreshToken.GetString() ?? string.Empty : string.Empty,
            TokenType = root.GetProperty("token_type").GetString() ?? string.Empty,
            Scope = root.TryGetProperty("scope", out var scope) ? scope.GetString() ?? string.Empty : string.Empty
        };

        Logger.LogInformation(
            "GitHub TokenResponse fields - AccessToken: {AccessToken}, TokenType: {TokenType}, Scope: {Scope}",
            tokenResponse.AccessToken[..Math.Min(tokenResponse.AccessToken.Length, 20)] + "...",
            tokenResponse.TokenType,
            tokenResponse.Scope);

        return tokenResponse;
    }
}
