namespace ServerEye.Core.Services.OAuth.Providers;

using System.Text.Json;
using Microsoft.Extensions.Logging;
using ServerEye.Core.Configuration;
using ServerEye.Core.DTOs.Auth;
using ServerEye.Core.Enums;
using ServerEye.Core.Interfaces.Services;
using ServerEye.Core.Services.OAuth;

public sealed class TelegramOAuthProvider(
    OAuthSettings oauthSettings,
    ILogger<TelegramOAuthProvider> logger) 
    : BaseOAuthProvider(oauthSettings, logger), IOAuthProvider
{
    public override OAuthProvider ProviderType => OAuthProvider.Telegram;

    public override bool IsEnabled()
    {
        return Settings.Telegram.Enabled;
    }

    public override async Task<OAuthChallengeResponseDto> CreateChallengeAsync(
        string state,
        string codeChallenge,
        Uri? returnUrl)
    {
        Logger.LogInformation(
            "CreateTelegramChallengeAsync called - State: {State}, ReturnUrl: {ReturnUrl}",
            state,
            returnUrl?.ToString() ?? "null");

        var settings = Settings.Telegram;
        
        // Add provider prefix to state so we can identify it in callback
        var stateWithProvider = $"telegram_{state}";
        var redirectUri = Uri.EscapeDataString(settings.RedirectUri.ToString());

        // Extract origin from RedirectUri (include port for Telegram origin parameter)
        var redirectUriObj = new Uri(settings.RedirectUri.ToString());
        var origin = $"{redirectUriObj.Scheme}://{redirectUriObj.Host}:{redirectUriObj.Port}";

        Logger.LogInformation(
            "Telegram OAuth settings - BotId: {BotId}, RedirectUri: {RedirectUri}, Origin: {Origin}",
            settings.BotId,
            settings.RedirectUri.ToString(),
            origin);

        // Telegram OAuth URL with correct parameters
        var url = $"https://oauth.telegram.org/auth?" +
                  $"bot_id={settings.BotId}&" + // Use bot_id from configuration
                  $"origin={Uri.EscapeDataString(origin)}&" + // Use frontend origin
                  $"request_access=write&" + // Request write access
                  $"redirect_uri={redirectUri}&" + // Use configured RedirectUri
                  $"return_url={redirectUri}&" + // Use return_url to force redirect to our page
                  $"state={stateWithProvider}";

        if (returnUrl != null)
        {
            url += $"&return_url={Uri.EscapeDataString(returnUrl.ToString())}";
        }

        Logger.LogInformation("Generated Telegram challenge URL: {Url}", url[..Math.Min(url.Length, 100)] + "...");

        return new OAuthChallengeResponseDto
        {
            ChallengeUrl = new Uri(url),
            State = stateWithProvider,
            CodeVerifier = string.Empty, // Generated by OAuthService
            Action = null
        };
    }

    public override async Task<OAuthUserInfoDto> GetUserInfoAsync(string accessToken, string? idToken, CancellationToken cancellationToken)
    {
        Logger.LogInformation(
            "GetTelegramUserInfoAsync called - AccessToken: {AccessToken}, IdToken: {IdToken}",
            accessToken[..Math.Min(accessToken.Length, 20)] + "...",
            string.IsNullOrEmpty(idToken) ? "NULL" : idToken[..Math.Min(idToken.Length, 20)] + "...");

        // Telegram OAuth returns user data as JSON in the "hash" parameter
        // The accessToken here is actually the user data JSON from Telegram
        try
        {
            var userData = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(accessToken)
                   ?? throw new InvalidOperationException("Failed to parse Telegram user data");
            
            Logger.LogInformation("Parsed Telegram user data: {UserData}", userData);

            // Extract user information from Telegram data
            // Telegram data comes directly, not nested in "user" field
            var userDict = userData; // userData is already a Dictionary<string, JsonElement>

            var userId = userDict.GetValueOrDefault("id").ValueKind == JsonValueKind.String 
                ? userDict.GetValueOrDefault("id").GetString() ?? "unknown" 
                : "unknown";
            var firstName = userDict.GetValueOrDefault("first_name").ValueKind == JsonValueKind.String 
                ? userDict.GetValueOrDefault("first_name").GetString() ?? string.Empty 
                : string.Empty;
            var lastName = userDict.GetValueOrDefault("last_name").ValueKind == JsonValueKind.String 
                ? userDict.GetValueOrDefault("last_name").GetString() ?? string.Empty 
                : string.Empty;
            var username = userDict.GetValueOrDefault("username").ValueKind == JsonValueKind.String 
                ? userDict.GetValueOrDefault("username").GetString() ?? string.Empty 
                : string.Empty;
            
            // Fallback to capitalized field names if lowercase ones don't exist
            if (string.IsNullOrEmpty(firstName))
            {
                firstName = userDict.GetValueOrDefault("FirstName").ValueKind == JsonValueKind.String 
                    ? userDict.GetValueOrDefault("FirstName").GetString() ?? string.Empty 
                    : string.Empty;
            }
            
            if (string.IsNullOrEmpty(lastName))
            {
                lastName = userDict.GetValueOrDefault("LastName").ValueKind == JsonValueKind.String 
                    ? userDict.GetValueOrDefault("LastName").GetString() ?? string.Empty 
                    : string.Empty;
            }
            
            if (string.IsNullOrEmpty(username))
            {
                username = userDict.GetValueOrDefault("Username").ValueKind == JsonValueKind.String 
                    ? userDict.GetValueOrDefault("Username").GetString() ?? string.Empty 
                    : string.Empty;
            }
                
            var name = $"{firstName} {lastName}".Trim();

            return new OAuthUserInfoDto
            {
                Id = userId,
                Email = null, // Telegram doesn't provide email
                Name = name,
                Username = username,
                AvatarUrl = null, // Avatar photos require separate API calls
                EmailVerified = false, // Telegram doesn't provide email verification
                RawData = userData.ToDictionary(
    kvp => kvp.Key, 
    kvp => kvp.Value.ValueKind == JsonValueKind.String 
        ? kvp.Value.GetString() ?? string.Empty
        : (object)kvp.Value.GetRawText()) // Keep as Dictionary for storage
            };
        }
        catch (Exception)
        {
            // Ultimate fallback - treat the access token as user ID
            var userData = new Dictionary<string, object>
            {
                ["id"] = accessToken,
                ["first_name"] = "Telegram",
                ["last_name"] = "User",
                ["username"] = "telegram_user"
            };

            return new OAuthUserInfoDto
            {
                Id = accessToken,
                Email = null, // Telegram doesn't provide email
                Name = "Telegram User",
                Username = "telegram_user",
                AvatarUrl = null,
                EmailVerified = false,
                RawData = userData
            };
        }
    }

    public override async Task<TokenResponseDto> ExchangeCodeAsync(string code, string codeVerifier, CancellationToken cancellationToken)
    {
        // Telegram OAuth flow is different - the "code" parameter contains user data
        // Telegram returns user data directly in the callback, not via token exchange
        // We treat the user data as the "access token" for consistency
        Logger.LogInformation("Processing Telegram OAuth - user data received directly in callback");

        return new TokenResponseDto
        {
            AccessToken = code, // This contains the Telegram user data JSON
            TokenType = "Bearer",
            ExpiresIn = 3600,
            IdToken = string.Empty, // Telegram doesn't use id_token
            RefreshToken = string.Empty, // Telegram doesn't use refresh tokens
            Scope = "telegram_user"
        };
    }
}
